<a href="https://colab.research.google.com/github/benvictoria21/MachineLearning/blob/master/beginner.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11493376/11490434 [==============================] - 0s 0us/step


In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.7534573 ,  0.1319778 ,  0.79651904, -0.16170588,  0.5272358 ,
        -0.06241427,  0.4347145 , -0.66929656,  0.4300043 ,  0.37578782]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.15154701, 0.08140334, 0.15821543, 0.0606872 , 0.12086502,
        0.06702222, 0.11018413, 0.0365303 , 0.10966637, 0.10387896]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.7027311

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2953 - accuracy: 0.9142
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1418 - accuracy: 0.9579
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1081 - accuracy: 0.9674
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0887 - accuracy: 0.9723
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0771 - accuracy: 0.9757


In [10]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0704 - accuracy: 0.9794


[0.07041016221046448, 0.9793999791145325]

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.43549402e-07, 1.28296023e-08, 5.74945079e-06, 2.16773420e-04,
        1.19671620e-10, 2.56975454e-06, 1.57143802e-13, 9.99738753e-01,
        3.30565513e-06, 3.24573521e-05],
       [1.18171855e-07, 1.34247794e-05, 9.99982119e-01, 4.12890472e-07,
        4.14876954e-13, 1.20371021e-06, 6.53261793e-07, 3.30922708e-13,
        2.02381966e-06, 2.27265651e-10],
       [4.33871179e-08, 9.99316335e-01, 1.07499487e-04, 1.03266102e-05,
        2.50635876e-05, 5.23092103e-06, 1.34527399e-05, 2.60622968e-04,
        2.60393892e-04, 1.14343140e-06],
       [9.99654412e-01, 7.44355966e-10, 2.06355951e-04, 9.35149131e-08,
        1.11848331e-09, 4.12200279e-06, 1.06594491e-07, 3.44050409e-06,
        6.61606281e-09, 1.31612891e-04],
       [2.67476366e-06, 3.66135539e-10, 3.42186922e-07, 1.09597478e-08,
        9.95328665e-01, 1.42885440e-07, 8.57402711e-07, 5.38072818e-05,
        9.44543501e-07, 4.61249379e-03]], dtype=float32)>