In [2]:
import pandas as pd 
import numpy as np 

In [28]:
df = pd.read_csv('dataset/Combined_News_DJIA.csv', encoding = 'ISO-8859-1')


df

Date  Label                                               Top1  \
0     2008-08-08      0  b"Georgia 'downs two Russian warplanes' as cou...   
1     2008-08-11      1  b'Why wont America and Nato help us? If they w...   
2     2008-08-12      0  b'Remember that adorable 9-year-old who sang a...   
3     2008-08-13      0  b' U.S. refuses Israel weapons to attack Iran:...   
4     2008-08-14      1  b'All the experts admit that we should legalis...   
...          ...    ...                                                ...   
1984  2016-06-27      0  Barclays and RBS shares suspended from trading...   
1985  2016-06-28      1  2,500 Scientists To Australia: If You Want To ...   
1986  2016-06-29      1                   Explosion At Airport In Istanbul   
1987  2016-06-30      1  Jamaica proposes marijuana dispensers for tour...   
1988  2016-07-01      1  A 117-year-old woman in Mexico City finally re...   

                                                   Top2  \
0               b'BREAKING: Musharraf to be impeached.'   
1           b'Bush puts foot down on Georgian conflict'   
2                    b"Russia 'ends Georgia operation'"   
3     b"When the president ordered to attack Tskhinv...   
4     b'War in South Osetia - 89 pictures made by a ...   
...                                                 ...   
1984  Pope says Church should ask forgiveness from g...   
1985  The personal details of 112,000 French police ...   
1986  Yemeni former president: Terrorism is the offs...   
1987  Stephen Hawking says pollution and 'stupidity'...   
1988   IMF chief backs Athens as permanent Olympic host   

                                                   Top3  \
0     b'Russia Today: Columns of troops roll into So...   
1     b"Jewish Georgian minister: Thanks to Israeli ...   
2     b'"If we had no sexual harassment we would hav...   
3     b' Israel clears troops who killed Reuters cam...   
4     b'Swedish wrestler Ara Abrahamian throws away ...   
...                                                 ...   
1984  Poland 'shocked' by xenophobic abuse of Poles ...   
1985  S&amp;P cuts United Kingdom sovereign credit r...   
1986  UK must accept freedom of movement to access E...   
1987  Boris Johnson says he will not run for Tory pa...   
1988  The president of France says if Brexit won, so...   

                                                   Top4  \
0     b'Russian tanks are moving towards the capital...   
1     b'Georgian army flees in disarray as Russians ...   
2     b"Al-Qa'eda is losing support in Iraq because ...   
3     b'Britain\'s policy of being tough on drugs is...   
4     b'Russia exaggerated the death toll in South O...   
...                                                 ...   
1984  There will be no second referendum, cabinet ag...   
1985                Huge helium deposit found in Africa   
1986  Devastated: scientists too late to captive bre...   
1987  Six gay men in Ivory Coast were abused and for...   
1988  British Man Who Must Give Police 24 Hours' Not...   

                                                   Top5  \
0     b"Afghan children raped with 'impunity,' U.N. ...   
1         b"Olympic opening ceremony fireworks 'faked'"   
2     b'Ceasefire in Georgia: Putin Outmaneuvers the...   
3     b'Body of 14 year old found in trunk; Latest (...   
4     b'Missile That Killed 9 Inside Pakistan May Ha...   
...                                                 ...   
1984      Scotland welcome to join EU, Merkel ally says   
1985  CEO of the South African state broadcaster qui...   
1986  British Labor Party leader Jeremy Corbyn loses...   
1987  Switzerland denies citizenship to Muslim immig...   
1988  100+ Nobel laureates urge Greenpeace to stop o...   

                                                   Top6  \
0     b'150 Russian tanks have entered South Ossetia...   
1     b'What were the Mossad with fraudulent New Zea...   
2     b'Why Microsoft and Intel tried to kill the XO...   
3  

In [4]:
df.head()

Date  Label                                               Top1  \
0  2008-08-08      0  b"Georgia 'downs two Russian warplanes' as cou...   
1  2008-08-11      1  b'Why wont America and Nato help us? If they w...   
2  2008-08-12      0  b'Remember that adorable 9-year-old who sang a...   
3  2008-08-13      0  b' U.S. refuses Israel weapons to attack Iran:...   
4  2008-08-14      1  b'All the experts admit that we should legalis...   

                                                Top2  \
0            b'BREAKING: Musharraf to be impeached.'   
1        b'Bush puts foot down on Georgian conflict'   
2                 b"Russia 'ends Georgia operation'"   
3  b"When the president ordered to attack Tskhinv...   
4  b'War in South Osetia - 89 pictures made by a ...   

                                                Top3  \
0  b'Russia Today: Columns of troops roll into So...   
1  b"Jewish Georgian minister: Thanks to Israeli ...   
2  b'"If we had no sexual harassment we would hav...   
3  b' Israel clears troops who killed Reuters cam...   
4  b'Swedish wrestler Ara Abrahamian throws away ...   

                                                Top4  \
0  b'Russian tanks are moving towards the capital...   
1  b'Georgian army flees in disarray as Russians ...   
2  b"Al-Qa'eda is losing support in Iraq because ...   
3  b'Britain\'s policy of being tough on drugs is...   
4  b'Russia exaggerated the death toll in South O...   

                                                Top5  \
0  b"Afghan children raped with 'impunity,' U.N. ...   
1      b"Olympic opening ceremony fireworks 'faked'"   
2  b'Ceasefire in Georgia: Putin Outmaneuvers the...   
3  b'Body of 14 year old found in trunk; Latest (...   
4  b'Missile That Killed 9 Inside Pakistan May Ha...   

                                                Top6  \
0  b'150 Russian tanks have entered South Ossetia...   
1  b'What were the Mossad with fraudulent New Zea...   
2  b'Why Microsoft and Intel tried to kill the XO...   
3  b'China has moved 10 *million* quake survivors...   
4  b"Rushdie Condemns Random House's Refusal to P...   

                                                Top7  \
0  b"Breaking: Georgia invades South Ossetia, Rus...   
1  b'Russia angered by Israeli military sale to G...   
2  b'Stratfor: The Russo-Georgian War and the Bal...   
3  b"Bush announces Operation Get All Up In Russi...   
4  b'Poland and US agree to missle defense deal. ...   

                                                Top8  ...  \
0  b"The 'enemy combatent' trials are nothing but...  ...   
1  b'An American citizen living in S.Ossetia blam...  ...   
2  b"I'm Trying to Get a Sense of This Whole Geor...  ...   
3             b'Russian forces sink Georgian ships '  ...   
4  b'Will the Russians conquer Tblisi? Bet on it,...  ...   

                                               Top16  \
0  b'Georgia Invades South Ossetia - if Russia ge...   
1  b'Israel and the US behind the Georgian aggres...   
2  b'U.S. troops still in Georgia (did you know t...   
3                      b'Elephants extinct by 2020?'   
4  b'Bank analyst forecast Georgian crisis 2 days...   

                                               Top17  \
0                b'Al-Qaeda Faces Islamist Backlash'   
1  b'"Do not believe TV, neither Russian nor Geor...   
2       b'Why Russias response to Georgia was right'   
3  b'US humanitarian missions soon in Georgia - i...   
4  b"Georgia confict could set back Russia's US r...   

                                               Top18  \
0  b'Condoleezza Rice: "The US would not act to p...   
1  b'Riots are still going on in Montreal (Canada...   
2  b'Gorbachev accuses U.S. of making a "serious ...   
3             b"Georgia's DDOS came from US sources"   
4  b'War in the Caucasus is as much the product o...   

                                               Top19  \
0  b'This is a busy day:  The European Union has ...   
1    b'China to overtake US as largest manufac

In [7]:
df.shape

(1989, 27)

In [8]:
train = df[df['Date']<'20150101']
test = df[df['Date'] > '20141231']

In [9]:
train.shape

(1863, 27)

In [10]:
test.shape

(378, 27)

In [11]:
data = train.iloc[:, 2:27]
data.replace("[^a-zA-Z]", " ", regex=True, inplace=True)

In [12]:
list1 = [i for i in range(25)]
new_Index = [str(i) for i in list1]
data.columns = new_Index
data.head(5)

0  \
0  b Georgia  downs two Russian warplanes  as cou...   
1  b Why wont America and Nato help us  If they w...   
2  b Remember that adorable   year old who sang a...   
3  b  U S  refuses Israel weapons to attack Iran ...   
4  b All the experts admit that we should legalis...   

                                                   1  \
0            b BREAKING  Musharraf to be impeached     
1        b Bush puts foot down on Georgian conflict    
2                 b Russia  ends Georgia operation     
3  b When the president ordered to attack Tskhinv...   
4  b War in South Osetia      pictures made by a ...   

                                                   2  \
0  b Russia Today  Columns of troops roll into So...   
1  b Jewish Georgian minister  Thanks to Israeli ...   
2  b  If we had no sexual harassment we would hav...   
3  b  Israel clears troops who killed Reuters cam...   
4  b Swedish wrestler Ara Abrahamian throws away ...   

                                                   3  \
0  b Russian tanks are moving towards the capital...   
1  b Georgian army flees in disarray as Russians ...   
2  b Al Qa eda is losing support in Iraq because ...   
3  b Britain  s policy of being tough on drugs is...   
4  b Russia exaggerated the death toll in South O...   

                                                   4  \
0  b Afghan children raped with  impunity   U N  ...   
1      b Olympic opening ceremony fireworks  faked     
2  b Ceasefire in Georgia  Putin Outmaneuvers the...   
3  b Body of    year old found in trunk  Latest  ...   
4  b Missile That Killed   Inside Pakistan May Ha...   

                                                   5  \
0  b     Russian tanks have entered South Ossetia...   
1  b What were the Mossad with fraudulent New Zea...   
2  b Why Microsoft and Intel tried to kill the XO...   
3  b China has moved     million  quake survivors...   
4  b Rushdie Condemns Random House s Refusal to P...   

                                                   6  \
0  b Breaking  Georgia invades South Ossetia  Rus...   
1  b Russia angered by Israeli military sale to G...   
2  b Stratfor  The Russo Georgian War and the Bal...   
3  b Bush announces Operation Get All Up In Russi...   
4  b Poland and US agree to missle defense deal  ...   

                                                   7  \
0  b The  enemy combatent  trials are nothing but...   
1  b An American citizen living in S Ossetia blam...   
2  b I m Trying to Get a Sense of This Whole Geor...   
3             b Russian forces sink Georgian ships     
4  b Will the Russians conquer Tblisi  Bet on it ...   

                                                   8  \
0  b Georgian troops retreat from S  Osettain cap...   
1  b Welcome To World War IV  Now In High Definit...   
2  b The US military was surprised by the timing ...   
3  b The commander of a Navy air reconnaissance s...   
4  b Russia exaggerating South Ossetian death tol...   

                                                   9  ...  \
0  b Did the U S  Prep Georgia for War with Russia    ...   
1  b Georgia s move  a mistake of monumental prop...  ...   
2    b U S  Beats War Drum as Iran Dumps the Dollar   ...   
3  b     of CNN readers  Russia s actions in Geor...  ...   
4  b  Musharraf expected to resign rather than fa...  ...   

                                                  15  \
0  b Georgia Invades South Ossetia   if Russia ge...   
1  b Israel and the US behind the Georgian aggres...   
2  b U S  troops still in Georgia  did you know t...   
3                      b Elephants extinct by          
4  b Bank analyst forecast Georgian crisis   days...   

                                                  16  \
0                b Al Qaeda Faces Islamist Backlash    
1  b  Do not believe TV  neither Russian nor Geor...   
2       b Why Russias response to Georgia was right    
3  b US humanitarian missions soon in Georgia   i...   
4  b Georgia confict could set bac

In [13]:
for index in new_Index:
    data[index] = data[index].str.lower()
data.head(2)

0  \
0  b georgia  downs two russian warplanes  as cou...   
1  b why wont america and nato help us  if they w...   

                                             1  \
0      b breaking  musharraf to be impeached     
1  b bush puts foot down on georgian conflict    

                                                   2  \
0  b russia today  columns of troops roll into so...   
1  b jewish georgian minister  thanks to israeli ...   

                                                   3  \
0  b russian tanks are moving towards the capital...   
1  b georgian army flees in disarray as russians ...   

                                                   4  \
0  b afghan children raped with  impunity   u n  ...   
1      b olympic opening ceremony fireworks  faked     

                                                   5  \
0  b     russian tanks have entered south ossetia...   
1  b what were the mossad with fraudulent new zea...   

                                                   6  \
0  b breaking  georgia invades south ossetia  rus...   
1  b russia angered by israeli military sale to g...   

                                                   7  \
0  b the  enemy combatent  trials are nothing but...   
1  b an american citizen living in s ossetia blam...   

                                                   8  \
0  b georgian troops retreat from s  osettain cap...   
1  b welcome to world war iv  now in high definit...   

                                                   9  ...  \
0  b did the u s  prep georgia for war with russia    ...   
1  b georgia s move  a mistake of monumental prop...  ...   

                                                  15  \
0  b georgia invades south ossetia   if russia ge...   
1  b israel and the us behind the georgian aggres...   

                                                  16  \
0                b al qaeda faces islamist backlash    
1  b  do not believe tv  neither russian nor geor...   

                                                  17  \
0  b condoleezza rice   the us would not act to p...   
1  b riots are still going on in montreal  canada...   

                                                  18  \
0  b this is a busy day   the european union has ...   
1    b china to overtake us as largest manufacturer    

                                                  19  \
0  b georgia will withdraw       soldiers from ir...   
1                     b war in south ossetia  pics     

                                                  20  \
0  b why the pentagon thinks attacking iran is a ...   
1  b israeli physicians group condemns state tort...   

                                                  21  \
0  b caucasus in crisis  georgia invades south os...   
1  b  russia has just beaten the united states ov...   

                                                  22  \
0  b indian shoe manufactory    and again in a se...   
1  b perhaps  the  question about the georgia   r...   

                                                  23  \
0  b visitors suffering from mental illnesses ban...   
1                 b russia is so much better at war    

                                                  24  
0           b no help for mexico s kidnapping surge   
1  b so this is what it s come to  trading sex fo...  

[2 rows x 25 columns]

In [14]:
' '.join(str(x) for x in data.iloc[1, 0:25]) 

'b why wont america and nato help us  if they wont help us now  why did we help them in iraq   b bush puts foot down on georgian conflict  b jewish georgian minister  thanks to israeli training  we re fending off russia   b georgian army flees in disarray as russians advance   gori abandoned to russia without a shot fired  b olympic opening ceremony fireworks  faked   b what were the mossad with fraudulent new zealand passports doing in iraq   b russia angered by israeli military sale to georgia  b an american citizen living in s ossetia blames u s  and georgian leaders for the genocide of innocent people  b welcome to world war iv  now in high definition   b georgia s move  a mistake of monumental proportions   b russia presses deeper into georgia  u s  says regime change is goal  b abhinav bindra wins first ever individual olympic gold medal for india  b  u s  ship heads for arctic to define territory  b drivers in a jerusalem taxi station threaten to quit rather than work for their 

In [15]:
headlines = []
for row in range(0, len(data.index)):
    headlines.append(' '.join(str(x) for x in data.iloc[row, 0:25]))
headlines[5]

'b mom of missing gay man  too bad he s not a    year old cheerleader  then they d still be looking for him  b russia  u s  poland missile deal won t go  unpunished   b the government has been accused of creating laws that have a chilling effect on freedom of expression in the uk in a critical report from the un s committee on human rights  b the italian government has lashed out at an influential catholic magazine which suggested fascism might be resurfacing within the government   b gorbachev  georgia started conflict in s  ossetia  b china fakes more than your girlfriend   ethnic minority  children at olympics ceremony were fake too   b the un s criticism of freedom of expression in the uk are valid  b russian general threatens nuclear strike on poland as bush demands moscow withdraws from georgia  b russia can inspect polish missile defence site  b russia georgia conflict fueled by rush to control caspian energy resources  b business week  victory in georgia gives russia the edge i

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier

In [17]:
countVector = CountVectorizer(ngram_range=(2,2))
#ngram(2,2) means it will combine the 2 words together and assign the value

trainDataset = countVector.fit_transform(headlines)
trainDataset[0] 

<1x403977 sparse matrix of type '<class 'numpy.int64'>'
	with 342 stored elements in Compressed Sparse Row format>

In [18]:
randomClassifier = RandomForestClassifier(n_estimators=200, criterion='entropy')
randomClassifier.fit(trainDataset, train['Label'])

RandomForestClassifier(criterion='entropy', n_estimators=200)

In [19]:
testTransform =[]
for row in range(0, len(test.index)):
    testTransform.append(' '.join(str(x) for x in test.iloc[row, 2:27]))
    
test_dataset = countVector.transform(testTransform)
predictions = randomClassifier.predict(test_dataset)
test.loc[1611, :]

Date                                            2015-01-02
Label                                                    1
Top1     Most cases of cancer are the result of sheer b...
Top2     Iran dismissed United States efforts to fight ...
Top3     Poll: One in 8 Germans would join anti-Muslim ...
Top4     UK royal family's Prince Andrew named in US la...
Top5     Some 40 asylum-seekers refused to leave the bu...
Top6     Pakistani boat blows self up after India navy ...
Top7     Sweden hit by third mosque arson attack in a week
Top8            940 cars set alight during French New Year
Top9     Salaries for top CEOs rose twice as fast as av...
Top10    Norway violated equal-pay law, judge says: Jud...
Top11    Imam wants radical recruiters of Muslim youth ...
Top12    Saudi Arabia beheaded 83 people in 2014, the m...
Top13    'A living hell' for slaves on remote South Kor...
Top14    Worlds 400 richest get richer, adding $92bn in...
Top15    Rental Car Stereos Infringe Copyright, Music R.

In [20]:
predictions

array([1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [21]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
matrix = confusion_matrix(test['Label'], predictions)
print(matrix)
score = accuracy_score(test['Label'], predictions)
print(score)
report = classification_report(test['Label'], predictions)
print(report)

[[134  52]
 [  2 190]]
0.8571428571428571
              precision    recall  f1-score   support

           0       0.99      0.72      0.83       186
           1       0.79      0.99      0.88       192

    accuracy                           0.86       378
   macro avg       0.89      0.86      0.85       378
weighted avg       0.88      0.86      0.85       378



In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
# implememt BAG OF WORDS
tfidfVector = TfidfVectorizer(ngram_range=(2,2))
#ngram(2,2) means it will combine the 2 words together and assign the value

trainDataset = tfidfVector.fit_transform(headlines)
randomClassifier = RandomForestClassifier(n_estimators=200, criterion='entropy')
randomClassifier.fit(trainDataset, train['Label'])

RandomForestClassifier(criterion='entropy', n_estimators=200)

In [23]:
testTransform =[]
for row in range(0, len(test.index)):
    testTransform.append(' '.join(str(x) for x in test.iloc[row, 2:27]))
    
test_dataset = tfidfVector.transform(testTransform)
predictions = randomClassifier.predict(test_dataset)
predictions

array([1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,

In [24]:
matrix = confusion_matrix(test['Label'], predictions)
print(matrix)
score = accuracy_score(test['Label'], predictions)
print(score)
report = classification_report(test['Label'], predictions)
print(report)

[[150  36]
 [ 28 164]]
0.8306878306878307
              precision    recall  f1-score   support

           0       0.84      0.81      0.82       186
           1       0.82      0.85      0.84       192

    accuracy                           0.83       378
   macro avg       0.83      0.83      0.83       378
weighted avg       0.83      0.83      0.83       378



In [25]:
from sklearn.naive_bayes import MultinomialNB
naive = MultinomialNB()
naive.fit(trainDataset, train['Label'])

MultinomialNB()

In [26]:
predictions = naive.predict(test_dataset)
predictions

array([1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [27]:
matrix = confusion_matrix(test['Label'], predictions)
print(matrix)
score = accuracy_score(test['Label'], predictions)
print(score)
report = classification_report(test['Label'], predictions)
print(report)

[[130  56]
 [  0 192]]
0.8518518518518519
              precision    recall  f1-score   support

           0       1.00      0.70      0.82       186
           1       0.77      1.00      0.87       192

    accuracy                           0.85       378
   macro avg       0.89      0.85      0.85       378
weighted avg       0.89      0.85      0.85       378

